# Generated by Django 3.1.4 on 2021-01-14 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CRN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('subject', models.CharField(default='', max_length=5)),
                ('section', models.CharField(default='', max_length=16)),
                ('course_name', models.CharField(default='', max_length=32)),
                ('status', models.CharField(default='', max_length=7)),
                ('followers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
