# Generated by Django 3.1.4 on 2021-01-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.IntegerField()),
                ('level', models.CharField(max_length=16)),
                ('section', models.CharField(max_length=16)),
                ('course_name', models.CharField(max_length=32)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRNTracker', models.IntegerField()),
                ('user', models.CharField(max_length=32)),
                ('user_number', models.CharField(max_length=10)),
            ],
        ),
    ]
