# Generated by Django 3.1.4 on 2021-01-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MODULE_scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='CRN',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='section',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.AddField(
            model_name='course',
            name='CRNR',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='course',
            name='course_nameR',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='course',
            name='followersR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='sectionR',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='course',
            name='statusR',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(default='', max_length=5),
        ),
    ]
