# Generated by Django 3.1.4 on 2021-01-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MODULE_scraping', '0002_auto_20210113_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CRNR',
            new_name='CRN',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_nameR',
            new_name='course_name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='followersR',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='sectionR',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='statusR',
            new_name='status',
        ),
    ]
