# Generated by Django 3.1.4 on 2021-01-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
