# Generated by Django 3.1.4 on 2021-01-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20210104_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='HOLDIN', max_length=32, unique=True, verbose_name='Student Username'),
        ),
    ]
