# Generated by Django 3.1.4 on 2021-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210104_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Default', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Username', max_length=32, unique=True, verbose_name='Student Username'),
        ),
    ]
